from .config import (
    AZURE_BASE_URL,
    AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_API_VERSION,
    AZURE_OPENAI_DEPLOYMENT,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    DATA_DIR,
    DOCUMENTS_STORE_PATH,
    EMBEDDING_MODEL,
    FAISS_INDEX_PATH,
    PROJECT_ROOT,
    TOP_K,
)
from .logger import get_logger
